### ISSUE TITLE
Day 1: Rails API基盤構築

### ISSUE THREAD

**Issue by nyg1971** [nyg1971/business_communication_platform#9]
# Day 1: Rails API基盤構築

## 🎯 目標
新規Rails APIアプリケーションの基盤構築完了

**想定作業時間**: 4-6時間  
**期限**: 6/17 (今日)

---

### Phase 1: 新規Railsアプリ作成
- [ ] Rails APIアプリ作成
```bash
rails new business_api --api --database=postgresql --skip-test
cd business_api
```
- [ ] バージョン確認
```bash
rails --version
bundle --version
```

### Phase 2: Gemfile設定
- [ ] 必要なGemを追加
```ruby
# 開発・テスト用
group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'pry-rails'
end

# 認証・API用
gem 'devise'
gem 'rack-cors'
gem 'jwt'
gem 'redis'
gem 'kaminari'
```
- [ ] `bundle install` 実行

### Phase 3: Docker環境構築
- [ ] `docker-compose.yml` 作成
```yaml
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: business_api_development
      POSTGRES_USER: business_user
      POSTGRES_PASSWORD: business_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
```
- [ ] `docker-compose up -d` でコンテナ起動
- [ ] `config/database.yml` の接続設定確認

### Phase 4: RuboCop設定
- [ ] `.rubocop.yml` 作成
```yaml
require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
```
- [ ] `bundle exec rubocop` で動作確認

### Phase 5: 基本設定ファイル作成
- [ ] CORS設定 (`config/application.rb`)
- [ ] ルーティング設定 (`config/routes.rb`)
- [ ] ヘルスチェックエンドポイント作成
```ruby
# app/controllers/health_controller.rb
class HealthController < ApplicationController
  def check
    render json: { 
      status: 'ok', 
      timestamp: Time.current,
      version: '1.0.0'
    }
  end
end
```

### Phase 6: データベース初期化
- [ ] `rails db:create` 実行
- [ ] アプリケーション起動確認 (`rails server`)
- [ ] ヘルスチェック動作確認 (`/health`)

### Phase 7: Git設定
- [ ] `.gitignore` 調整
- [ ] 初回コミット
```bash
git init
git add .
git commit -m "Initial commit: Rails API app with basic setup"
```
- [ ] GitHubリポジトリ作成・プッシュ

---

## ✅ 完成チェックリスト

動作確認項目：
- [ ] Rails APIアプリが正常に起動する
- [ ] PostgreSQLデータベースに接続できる  
- [ ] Redisコンテナが起動している
- [ ] `/health` エンドポイントが正常に応答する
- [ ] RuboCopが実行できる
- [ ] GitHubにコードがプッシュされている

---

### PostgreSQL接続エラー
```ruby
# config/database.yml を確認
development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: business_user
  password: business_password
```

### Docker関連エラー
```bash
# ポート競合確認
lsof -i :5432
docker-compose down
```

### RuboCop違反
- 初期段階では違反があってもOK
- 次のフェーズで段階的に修正予定

---

## 💡 ポイント

技術：
- Rails 7 APIモードの基本構成
- Docker Composeによる開発環境構築
- PostgreSQL + Redis のマルチDB構成
- RuboCopによるコード品質管理
- CORS設定とAPI設計基礎

---

## 🔄 次のステップ

Day 2では以下を予定：
- [ ] Devise設定
- [ ] JWT認証実装  
- [ ] User モデル作成
- [ ] 認証API動作確認

---

## 📝 作業ログ

**開始時刻**: ___:___  
**完了時刻**: ___:___  
**実作業時間**: ___ 時間

### メモ

---

**Assignees**: @nyg1971 
**Labels**: `day1`, `setup`, `rails-api`, `docker`  
**Milestone**: Week 1 - API基盤構築
